language: node_js
node_js:
  - 0.12

script: node_modules/karma/bin/karma start tests/my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install

addons:
    code_climate:
        repo_token: e3ea65e18129457ab3f443a120ce70c4b155db223e3b4b87de5c55dadaab9391
